version: "3"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      NODE_ENV: production
      accessKeyId: ASIAQXY5S2ECGBFEYWHM
      secretAccessKey: 90mw+yxJYE2fqDoRd6IX4JkmLewuBWZDuCe3V4mL
      sessionToken: FwoGZXIvYXdzEAoaDFsu01a+pg1GiOKX/SLIAU5k7OSNZE7eJuSmd8Ugf6x5Ny8eKK13qGIRIBmTk79+/GU6/VbLVztS/t3MMYTXZoaARiQttPMilRYb1o8RJuc5PB5Ro7c+bl4iUw7jlJ3JaxlUUQEEavWrOUsu8L5MJJq0mazIUY0friDGHfjdVloD/RrGL+xyxl6MVwnFoofuik+vtxjVquszUo/6HtFj8BAyM+jpsiC/ViOW3VzZpa8Zqa90JLwT7oAzUOxCfKM3/7HSGouKAzI1IRKCW6zj1QX4ueiwhD9EKPiRi6MGMi1iKbUg+e0yxGisyQmtBHr3zSjiFoE9nkN9zC7ApbJrMLU4bndrbnwG34CqwsA=

    restart: always
    volumes:
      - efs_volume:/var/www/html
volumes:
  efs_volume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=fs-0153f3d48579c6584.efs.us-east-1.amazonaws.com,rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport"
      device: ":/"
